import type { Trail } from "./types";

/**
 * Seed dataset.
 *
 * Coordinates are trailhead-accurate to roughly a hundred metres, which is
 * well inside the resolution of every weather model we query. Attributes
 * like `surface`, `aspect` and `waterCrossings` are the hand-curated part:
 * they are what let the scoring engine say something a generic forecast
 * cannot, and they are exactly the fields a real deployment would move into
 * PostGIS and source from OSM plus land-manager data.
 */
export const TRAILS: Trail[] = [
  {
    id: "timpanogos-timpooneke",
    name: "Mount Timpanogos (Timpooneke)",
    region: "American Fork Canyon",
    state: "UT",
    lat: 40.4319,
    lon: -111.6069,
    elevationFt: 7360,
    gainFt: 4580,
    distanceMi: 14.7,
    activities: ["hike", "trail_run"],
    surface: "mixed",
    aspect: "NE",
    exposed: true,
    waterCrossings: 3,
    blurb: "Long alpine day to an 11,700 ft summit. Holds snow in the basin well into July.",
  },
  {
    id: "y-mountain",
    name: "Y Mountain",
    region: "Provo",
    state: "UT",
    lat: 40.2489,
    lon: -111.6329,
    elevationFt: 5100,
    gainFt: 1070,
    distanceMi: 2.4,
    activities: ["hike", "trail_run"],
    surface: "gravel",
    aspect: "W",
    exposed: true,
    waterCrossings: 0,
    blurb: "Short, steep, and completely unshaded. A furnace on summer afternoons.",
  },
  {
    id: "stewart-falls",
    name: "Stewart Falls",
    region: "Sundance",
    state: "UT",
    lat: 40.4056,
    lon: -111.6106,
    elevationFt: 6900,
    gainFt: 640,
    distanceMi: 3.5,
    activities: ["hike", "trail_run"],
    surface: "dirt",
    aspect: "NE",
    exposed: false,
    waterCrossings: 1,
    blurb: "Shaded aspen traverse to a 200 ft waterfall. Forgiving in heat.",
  },
  {
    id: "lake-blanche",
    name: "Lake Blanche",
    region: "Big Cottonwood Canyon",
    state: "UT",
    lat: 40.6265,
    lon: -111.7124,
    elevationFt: 6320,
    gainFt: 2720,
    distanceMi: 6.9,
    activities: ["hike", "trail_run"],
    surface: "rock",
    aspect: "NW",
    exposed: true,
    waterCrossings: 2,
    blurb: "Relentless climb to a quartzite basin under Sundial Peak.",
  },
  {
    id: "donut-falls",
    name: "Donut Falls",
    region: "Big Cottonwood Canyon",
    state: "UT",
    lat: 40.6318,
    lon: -111.6975,
    elevationFt: 7600,
    gainFt: 440,
    distanceMi: 3.0,
    activities: ["hike"],
    surface: "dirt",
    aspect: "N",
    exposed: false,
    waterCrossings: 2,
    blurb: "Short family route to a hole-in-the-rock waterfall. Slick when wet.",
  },
  {
    id: "desolation-lake",
    name: "Desolation Lake",
    region: "Mill Creek Canyon",
    state: "UT",
    lat: 40.6866,
    lon: -111.658,
    elevationFt: 7100,
    gainFt: 2320,
    distanceMi: 8.3,
    activities: ["hike", "trail_run", "mtb"],
    surface: "dirt",
    aspect: "N",
    exposed: false,
    waterCrossings: 1,
    blurb: "Shaded singletrack to a cirque lake. Prime when the valley bakes.",
  },
  {
    id: "wasatch-crest",
    name: "Wasatch Crest Trail",
    region: "Park City / Mill Creek",
    state: "UT",
    lat: 40.66,
    lon: -111.59,
    elevationFt: 9200,
    gainFt: 1500,
    distanceMi: 12.4,
    activities: ["mtb", "trail_run"],
    surface: "dirt",
    aspect: "mixed",
    exposed: true,
    waterCrossings: 0,
    blurb: "The classic high-alpine ridge ride. Fully exposed to weather and wind.",
  },
  {
    id: "corner-canyon",
    name: "Corner Canyon (Clark's Trail)",
    region: "Draper",
    state: "UT",
    lat: 40.488,
    lon: -111.833,
    elevationFt: 4900,
    gainFt: 900,
    distanceMi: 7.5,
    activities: ["mtb", "trail_run", "hike"],
    surface: "clay",
    aspect: "W",
    exposed: true,
    waterCrossings: 0,
    blurb: "Flowy foothill network. Clay soil turns to peanut butter after rain.",
  },
  {
    id: "bonneville-shoreline-slc",
    name: "Bonneville Shoreline (City Creek)",
    region: "Salt Lake City",
    state: "UT",
    lat: 40.7686,
    lon: -111.8226,
    elevationFt: 4700,
    gainFt: 620,
    distanceMi: 5.2,
    activities: ["hike", "trail_run", "mtb"],
    surface: "gravel",
    aspect: "SW",
    exposed: true,
    waterCrossings: 0,
    blurb: "Valley-floor foothill trail. First to dry out, first to fill with inversion smog.",
  },
  {
    id: "mount-olympus",
    name: "Mount Olympus",
    region: "Salt Lake Valley",
    state: "UT",
    lat: 40.6497,
    lon: -111.8046,
    elevationFt: 4900,
    gainFt: 4100,
    distanceMi: 7.0,
    activities: ["hike"],
    surface: "rock",
    aspect: "W",
    exposed: true,
    waterCrossings: 0,
    blurb: "Brutally steep west face with no shade and a scramble finish.",
  },
  {
    id: "red-pine-lake",
    name: "Red Pine Lake",
    region: "Little Cottonwood Canyon",
    state: "UT",
    lat: 40.5722,
    lon: -111.6817,
    elevationFt: 7680,
    gainFt: 2000,
    distanceMi: 6.8,
    activities: ["hike", "trail_run"],
    surface: "rock",
    aspect: "N",
    exposed: false,
    waterCrossings: 2,
    blurb: "Granite basin hike. North aspect keeps snow lingering past Memorial Day.",
  },
  {
    id: "bells-canyon",
    name: "Bells Canyon Lower Falls",
    region: "Sandy",
    state: "UT",
    lat: 40.5647,
    lon: -111.7852,
    elevationFt: 5200,
    gainFt: 1400,
    distanceMi: 4.6,
    activities: ["hike"],
    surface: "rock",
    aspect: "W",
    exposed: false,
    waterCrossings: 1,
    blurb: "Boulder-strewn climb to a waterfall. The crossing runs high in spring melt.",
  },
  {
    id: "slickrock-moab",
    name: "Slickrock Bike Trail",
    region: "Moab",
    state: "UT",
    lat: 38.5808,
    lon: -109.5205,
    elevationFt: 4600,
    gainFt: 1500,
    distanceMi: 10.5,
    activities: ["mtb"],
    surface: "rock",
    aspect: "mixed",
    exposed: true,
    waterCrossings: 0,
    blurb: "Sandstone fins with zero shade. Rideable wet, lethal in July heat.",
  },
  {
    id: "delicate-arch",
    name: "Delicate Arch",
    region: "Arches National Park",
    state: "UT",
    lat: 38.7436,
    lon: -109.4993,
    elevationFt: 4830,
    gainFt: 620,
    distanceMi: 3.2,
    activities: ["hike"],
    surface: "rock",
    aspect: "SW",
    exposed: true,
    waterCrossings: 0,
    blurb: "Open slickrock bench with no shade or water. Heat is the whole risk.",
  },
  {
    id: "angels-landing",
    name: "Angels Landing",
    region: "Zion National Park",
    state: "UT",
    lat: 37.269,
    lon: -112.9469,
    elevationFt: 4280,
    gainFt: 1500,
    distanceMi: 4.4,
    activities: ["hike"],
    surface: "rock",
    aspect: "E",
    exposed: true,
    waterCrossings: 0,
    blurb: "Chained ridge scramble with severe exposure. Wind and wet rock are disqualifying.",
  },
  {
    id: "little-cottonwood-crag",
    name: "Little Cottonwood Crags",
    region: "Little Cottonwood Canyon",
    state: "UT",
    lat: 40.5714,
    lon: -111.7639,
    elevationFt: 5500,
    gainFt: 300,
    distanceMi: 1.2,
    activities: ["climb"],
    surface: "rock",
    aspect: "S",
    exposed: true,
    waterCrossings: 0,
    blurb: "South-facing granite. Warm in shoulder season, greasy after any rain.",
  },
  {
    id: "american-fork-crag",
    name: "American Fork Canyon Crags",
    region: "American Fork Canyon",
    state: "UT",
    lat: 40.4581,
    lon: -111.7122,
    elevationFt: 5800,
    gainFt: 400,
    distanceMi: 1.0,
    activities: ["climb"],
    surface: "rock",
    aspect: "N",
    exposed: false,
    waterCrossings: 0,
    blurb: "Steep limestone sport climbing. Shaded and cool when the valley is hot.",
  },
  {
    id: "maple-canyon",
    name: "Maple Canyon",
    region: "Sanpete County",
    state: "UT",
    lat: 39.5433,
    lon: -111.6858,
    elevationFt: 6600,
    gainFt: 350,
    distanceMi: 1.5,
    activities: ["climb", "hike"],
    surface: "rock",
    aspect: "mixed",
    exposed: false,
    waterCrossings: 0,
    blurb: "Cobblestone conglomerate in a narrow, shaded canyon. Stays cool all summer.",
  },
];

export const TRAILS_BY_ID: Record<string, Trail> = Object.fromEntries(
  TRAILS.map((t) => [t.id, t]),
);

export function getTrail(id: string): Trail | undefined {
  return TRAILS_BY_ID[id];
}
