import type { Trail } from "./types";
import { OPENBETA_AREAS } from "./data/climbingAreas";

/**
 * Seed dataset.
 *
 * Coordinates are trailhead-accurate to roughly a hundred metres, which is
 * well inside the resolution of every weather model we query. Attributes
 * like `surface`, `aspect` and `waterCrossings` are the hand-curated part:
 * they are what let the scoring engine say something a generic forecast
 * cannot, and they are exactly the fields a real deployment would move into
 * PostGIS and source from OSM plus land-manager data.
 */
const CURATED_TRAILS: Trail[] = [
  {
    id: "timpanogos-timpooneke",
    name: "Mount Timpanogos (Timpooneke)",
    region: "American Fork Canyon",
    state: "UT",
    lat: 40.4319,
    lon: -111.6069,
    elevationFt: 7360,
    gainFt: 4580,
    distanceMi: 14.7,
    activities: ["hike", "trail_run"],
    surface: "mixed",
    aspect: "NE",
    exposed: true,
    waterCrossings: 3,
    blurb: "Long alpine day to an 11,700 ft summit. Holds snow in the basin well into July.",
  },
  {
    id: "y-mountain",
    name: "Y Mountain",
    region: "Provo",
    state: "UT",
    lat: 40.2489,
    lon: -111.6329,
    elevationFt: 5100,
    gainFt: 1070,
    distanceMi: 2.4,
    activities: ["hike", "trail_run"],
    surface: "gravel",
    aspect: "W",
    exposed: true,
    waterCrossings: 0,
    blurb: "Short, steep, and completely unshaded. A furnace on summer afternoons.",
  },
  {
    id: "stewart-falls",
    name: "Stewart Falls",
    region: "Sundance",
    state: "UT",
    lat: 40.4056,
    lon: -111.6106,
    elevationFt: 6900,
    gainFt: 640,
    distanceMi: 3.5,
    activities: ["hike", "trail_run"],
    surface: "dirt",
    aspect: "NE",
    exposed: false,
    waterCrossings: 1,
    blurb: "Shaded aspen traverse to a 200 ft waterfall. Forgiving in heat.",
  },
  {
    id: "lake-blanche",
    name: "Lake Blanche",
    region: "Big Cottonwood Canyon",
    state: "UT",
    lat: 40.6265,
    lon: -111.7124,
    elevationFt: 6320,
    gainFt: 2720,
    distanceMi: 6.9,
    activities: ["hike", "trail_run"],
    surface: "rock",
    aspect: "NW",
    exposed: true,
    waterCrossings: 2,
    blurb: "Relentless climb to a quartzite basin under Sundial Peak.",
  },
  {
    id: "donut-falls",
    name: "Donut Falls",
    region: "Big Cottonwood Canyon",
    state: "UT",
    lat: 40.6318,
    lon: -111.6975,
    elevationFt: 7600,
    gainFt: 440,
    distanceMi: 3.0,
    activities: ["hike"],
    surface: "dirt",
    aspect: "N",
    exposed: false,
    waterCrossings: 2,
    blurb: "Short family route to a hole-in-the-rock waterfall. Slick when wet.",
  },
  {
    id: "desolation-lake",
    name: "Desolation Lake",
    region: "Mill Creek Canyon",
    state: "UT",
    lat: 40.6866,
    lon: -111.658,
    elevationFt: 7100,
    gainFt: 2320,
    distanceMi: 8.3,
    activities: ["hike", "trail_run", "mtb"],
    surface: "dirt",
    aspect: "N",
    exposed: false,
    waterCrossings: 1,
    blurb: "Shaded singletrack to a cirque lake. Prime when the valley bakes.",
  },
  {
    id: "wasatch-crest",
    name: "Wasatch Crest Trail",
    region: "Park City / Mill Creek",
    state: "UT",
    lat: 40.66,
    lon: -111.59,
    elevationFt: 9200,
    gainFt: 1500,
    distanceMi: 12.4,
    activities: ["mtb", "trail_run"],
    surface: "dirt",
    aspect: "mixed",
    exposed: true,
    waterCrossings: 0,
    blurb: "The classic high-alpine ridge ride. Fully exposed to weather and wind.",
  },
  {
    id: "corner-canyon",
    name: "Corner Canyon (Clark's Trail)",
    region: "Draper",
    state: "UT",
    lat: 40.488,
    lon: -111.833,
    elevationFt: 4900,
    gainFt: 900,
    distanceMi: 7.5,
    activities: ["mtb", "trail_run", "hike"],
    surface: "clay",
    aspect: "W",
    exposed: true,
    waterCrossings: 0,
    blurb: "Flowy foothill network. Clay soil turns to peanut butter after rain.",
  },
  {
    id: "bonneville-shoreline-slc",
    name: "Bonneville Shoreline (City Creek)",
    region: "Salt Lake City",
    state: "UT",
    lat: 40.7686,
    lon: -111.8226,
    elevationFt: 4700,
    gainFt: 620,
    distanceMi: 5.2,
    activities: ["hike", "trail_run", "mtb"],
    surface: "gravel",
    aspect: "SW",
    exposed: true,
    waterCrossings: 0,
    blurb: "Valley-floor foothill trail. First to dry out, first to fill with inversion smog.",
  },
  {
    id: "mount-olympus",
    name: "Mount Olympus",
    region: "Salt Lake Valley",
    state: "UT",
    lat: 40.6497,
    lon: -111.8046,
    elevationFt: 4900,
    gainFt: 4100,
    distanceMi: 7.0,
    activities: ["hike"],
    surface: "rock",
    aspect: "W",
    exposed: true,
    waterCrossings: 0,
    blurb: "Brutally steep west face with no shade and a scramble finish.",
  },
  {
    id: "red-pine-lake",
    name: "Red Pine Lake",
    region: "Little Cottonwood Canyon",
    state: "UT",
    lat: 40.5722,
    lon: -111.6817,
    elevationFt: 7680,
    gainFt: 2000,
    distanceMi: 6.8,
    activities: ["hike", "trail_run"],
    surface: "rock",
    aspect: "N",
    exposed: false,
    waterCrossings: 2,
    blurb: "Granite basin hike. North aspect keeps snow lingering past Memorial Day.",
  },
  {
    id: "bells-canyon",
    name: "Bells Canyon Lower Falls",
    region: "Sandy",
    state: "UT",
    lat: 40.5647,
    lon: -111.7852,
    elevationFt: 5200,
    gainFt: 1400,
    distanceMi: 4.6,
    activities: ["hike"],
    surface: "rock",
    aspect: "W",
    exposed: false,
    waterCrossings: 1,
    blurb: "Boulder-strewn climb to a waterfall. The crossing runs high in spring melt.",
  },
  {
    id: "slickrock-moab",
    name: "Slickrock Bike Trail",
    region: "Moab",
    state: "UT",
    lat: 38.5808,
    lon: -109.5205,
    elevationFt: 4600,
    gainFt: 1500,
    distanceMi: 10.5,
    activities: ["mtb"],
    surface: "rock",
    aspect: "mixed",
    exposed: true,
    waterCrossings: 0,
    blurb: "Sandstone fins with zero shade. Rideable wet, lethal in July heat.",
  },
  {
    id: "delicate-arch",
    name: "Delicate Arch",
    region: "Arches National Park",
    state: "UT",
    lat: 38.7436,
    lon: -109.4993,
    elevationFt: 4830,
    gainFt: 620,
    distanceMi: 3.2,
    activities: ["hike"],
    surface: "rock",
    aspect: "SW",
    exposed: true,
    waterCrossings: 0,
    blurb: "Open slickrock bench with no shade or water. Heat is the whole risk.",
  },
  {
    id: "angels-landing",
    name: "Angels Landing",
    region: "Zion National Park",
    state: "UT",
    lat: 37.269,
    lon: -112.9469,
    elevationFt: 4280,
    gainFt: 1500,
    distanceMi: 4.4,
    activities: ["hike"],
    surface: "rock",
    aspect: "E",
    exposed: true,
    waterCrossings: 0,
    blurb: "Chained ridge scramble with severe exposure. Wind and wet rock are disqualifying.",
  },
  {
    id: "little-cottonwood-crag",
    name: "Little Cottonwood Crags",
    region: "Little Cottonwood Canyon",
    state: "UT",
    lat: 40.5714,
    lon: -111.7639,
    elevationFt: 5500,
    gainFt: 300,
    distanceMi: 1.2,
    activities: ["climb"],
    surface: "rock",
    aspect: "S",
    exposed: true,
    waterCrossings: 0,
    rockType: "granite",
    blurb: "South-facing granite. Catches winter sun; dries within hours of rain.",
  },
  {
    id: "american-fork-crag",
    name: "American Fork Canyon Crags",
    region: "American Fork Canyon",
    state: "UT",
    lat: 40.4581,
    lon: -111.7122,
    elevationFt: 5800,
    gainFt: 400,
    distanceMi: 1.0,
    activities: ["climb"],
    surface: "rock",
    aspect: "N",
    exposed: false,
    waterCrossings: 0,
    rockType: "limestone",
    blurb: "Steep limestone sport climbing. Shaded and cool when the valley bakes, but seeps for a day after rain.",
  },
  {
    id: "maple-canyon",
    name: "Maple Canyon",
    region: "Sanpete County",
    state: "UT",
    lat: 39.5433,
    lon: -111.6858,
    elevationFt: 6600,
    gainFt: 350,
    distanceMi: 1.5,
    activities: ["climb", "hike"],
    surface: "rock",
    aspect: "mixed",
    exposed: false,
    waterCrossings: 0,
    rockType: "conglomerate",
    blurb: "Cobblestone conglomerate in a narrow, shaded canyon. Stays cool all summer; wet cobbles pull out.",
  },
  {
    id: "gate-buttress-lcc",
    name: "Gate Buttress (Little Cottonwood)",
    region: "Little Cottonwood Canyon",
    state: "UT",
    lat: 40.5723,
    lon: -111.7616,
    elevationFt: 6000,
    gainFt: 500,
    distanceMi: 0.8,
    activities: ["climb"],
    surface: "rock",
    aspect: "S",
    exposed: true,
    waterCrossings: 0,
    rockType: "granite",
    blurb: "Fine-grained white granite, the first US climbing area on the National Register. South-facing walls hold winter sun.",
  },
  {
    id: "storm-mountain-bcc",
    name: "Storm Mountain (Big Cottonwood)",
    region: "Big Cottonwood Canyon",
    state: "UT",
    lat: 40.6197,
    lon: -111.7297,
    elevationFt: 5900,
    gainFt: 250,
    distanceMi: 0.4,
    activities: ["climb"],
    surface: "rock",
    aspect: "SW",
    exposed: true,
    waterCrossings: 0,
    rockType: "quartzite",
    blurb: "Roadside quartzite with trad and bolted lines. Climbable year-round and dries fast.",
  },
  {
    id: "rock-canyon-provo",
    name: "Rock Canyon",
    region: "Provo",
    state: "UT",
    lat: 40.26,
    lon: -111.61,
    elevationFt: 5200,
    gainFt: 400,
    distanceMi: 0.9,
    activities: ["climb", "hike"],
    surface: "rock",
    aspect: "S",
    exposed: true,
    waterCrossings: 0,
    rockType: "quartzite",
    blurb: "Provo's backyard crag, minutes from campus. Quartzite and limestone, south-facing, climbable most of the winter.",
  },
  {
    id: "logan-canyon-china-cave",
    name: "China Cave (Logan Canyon)",
    region: "Logan Canyon",
    state: "UT",
    lat: 41.7561,
    lon: -111.6403,
    elevationFt: 5400,
    gainFt: 350,
    distanceMi: 0.6,
    activities: ["climb"],
    surface: "rock",
    aspect: "S",
    exposed: true,
    waterCrossings: 0,
    rockType: "limestone",
    blurb: "Steep limestone in a canyon with 400+ sport routes. The cave stays dry through light rain.",
  },
  {
    id: "ogden-9th-street",
    name: "9th Street Crag",
    region: "Ogden",
    state: "UT",
    lat: 41.2372,
    lon: -111.9333,
    elevationFt: 4700,
    gainFt: 200,
    distanceMi: 0.3,
    activities: ["climb"],
    surface: "rock",
    aspect: "W",
    exposed: true,
    waterCrossings: 0,
    rockType: "quartzite",
    blurb: "Short approach, 5.6 through 5.13. A winter staple when the canyons are buried.",
  },
  {
    id: "indian-creek-supercrack",
    name: "Supercrack Buttress (Indian Creek)",
    region: "Indian Creek",
    state: "UT",
    lat: 38.0369,
    lon: -109.5486,
    elevationFt: 5000,
    gainFt: 400,
    distanceMi: 0.5,
    activities: ["climb"],
    surface: "rock",
    aspect: "W",
    exposed: true,
    waterCrossings: 0,
    rockType: "sandstone",
    blurb: "The world's best splitter cracks, in Wingate sandstone. Never climb it wet \u2014 saturated Wingate breaks.",
  },
  {
    id: "wall-street-moab",
    name: "Wall Street",
    region: "Moab",
    state: "UT",
    lat: 38.5346,
    lon: -109.5931,
    elevationFt: 4000,
    gainFt: 50,
    distanceMi: 0.1,
    activities: ["climb"],
    surface: "rock",
    aspect: "E",
    exposed: true,
    waterCrossings: 0,
    rockType: "sandstone",
    blurb: "Belay from the roadside on Wingate sandstone above the Colorado. Morning sun, afternoon shade.",
  },
  {
    id: "zion-namaste-wall",
    name: "Namaste Wall",
    region: "Zion National Park",
    state: "UT",
    lat: 37.19,
    lon: -112.988,
    elevationFt: 3900,
    gainFt: 300,
    distanceMi: 0.5,
    activities: ["climb"],
    surface: "rock",
    aspect: "SE",
    exposed: true,
    waterCrossings: 0,
    rockType: "sandstone",
    blurb: "Navajo sandstone sport routes below the big walls. Needs days of sun after a storm.",
  },
  {
    id: "joes-valley",
    name: "Joe's Valley",
    region: "Orangeville",
    state: "UT",
    lat: 39.2833,
    lon: -111.2167,
    elevationFt: 6800,
    gainFt: 150,
    distanceMi: 0.4,
    activities: ["climb"],
    surface: "rock",
    aspect: "mixed",
    exposed: true,
    waterCrossings: 0,
    rockType: "sandstone",
    blurb: "World-class sandstone bouldering at altitude. Cool temps mean friction; wet rock means broken holds.",
  },
  {
    id: "chuckwalla-st-george",
    name: "Chuckwalla Wall",
    region: "St. George",
    state: "UT",
    lat: 37.1358,
    lon: -113.6169,
    elevationFt: 2900,
    gainFt: 120,
    distanceMi: 0.3,
    activities: ["climb"],
    surface: "rock",
    aspect: "S",
    exposed: true,
    waterCrossings: 0,
    rockType: "sandstone",
    blurb: "Sunny southern Utah sandstone, five minutes from the car. The winter answer when the north is frozen.",
  },
  {
    id: "virgin-river-gorge",
    name: "Virgin River Gorge",
    region: "Littlefield",
    state: "AZ",
    lat: 36.9944,
    lon: -113.7856,
    elevationFt: 2200,
    gainFt: 250,
    distanceMi: 0.4,
    activities: ["climb"],
    surface: "rock",
    aspect: "N",
    exposed: false,
    waterCrossings: 0,
    rockType: "limestone",
    blurb: "Overhanging limestone beside the interstate. Steep enough to stay dry in light rain; a winter destination.",
  },
  {
    id: "ibex-utah",
    name: "Ibex",
    region: "West Desert",
    state: "UT",
    lat: 39.4667,
    lon: -113.3833,
    elevationFt: 4600,
    gainFt: 100,
    distanceMi: 0.3,
    activities: ["climb"],
    surface: "rock",
    aspect: "mixed",
    exposed: true,
    waterCrossings: 0,
    rockType: "quartzite",
    blurb: "Remote quartzite bouldering on a dry lakebed. Bone dry almost always, and no shade whatsoever.",
  },
];

/**
 * Hand-curated areas carry verified terrain attributes; imported ones bring
 * breadth. Curated entries come first so that where the two overlap, the
 * better-attributed record is the one a proximity or prominence cap keeps.
 */
export const TRAILS: Trail[] = [...CURATED_TRAILS, ...OPENBETA_AREAS];

export const TRAILS_BY_ID: Record<string, Trail> = Object.fromEntries(
  TRAILS.map((t) => [t.id, t]),
);

export function getTrail(id: string): Trail | undefined {
  return TRAILS_BY_ID[id];
}
