/**
 * Refresh the OpenStreetMap line snapshot.
 *
 *   npx tsx scripts/import-osm-lines.ts
 *
 * Queries Overpass once per place in OSM_SPECS (politely, one at a time) and
 * rewrites src/lib/data/osmLines.ts. Places that fail keep their old lines.
 */
import { writeFileSync } from "node:fs";
import { OSM_SPECS, fetchLinesLive } from "../src/lib/sources/osmLines";
import { OSM_LINES } from "../src/lib/data/osmLines";

async function main() {
  const out: Record<string, [number, number][][]> = { ...OSM_LINES };
  for (const id of Object.keys(OSM_SPECS)) {
    try {
      out[id] = await fetchLinesLive(id);
      console.log(`${id}: ${out[id]!.length} runs`);
    } catch (error) {
      console.warn(`${id}: kept previous (${String(error)})`);
    }
    await new Promise((resolve) => setTimeout(resolve, 1500));
  }
  const header = `/* Generated by scripts/import-osm-lines.ts on ${new Date().toISOString().slice(0, 10)}. Data © OpenStreetMap contributors, ODbL. */\n`;
  writeFileSync(
    new URL("../src/lib/data/osmLines.ts", import.meta.url),
    `${header}export const OSM_LINES: Record<string, [number, number][][]> = ${JSON.stringify(out)};\n`,
  );
}

void main();
