/**
 * Refresh the Utah climbing-area snapshot from OpenBeta.
 *
 *   npx tsx scripts/import-openbeta-areas.ts
 *
 * Walks the whole Utah area tree and keeps every leaf area -- a crag or
 * boulder field, the thing a climber actually drives to -- that has three or
 * more recorded routes and a location.
 *
 * Why a snapshot and not a live call: the walk is a few thousand requests and
 * takes minutes, which no request handler can wear. Routes themselves are
 * still fetched live per area, so a new route appears immediately; only the
 * list of *places* is frozen, and crags do not appear weekly.
 *
 * This runs in CI (see .github/workflows/refresh-climbing.yml) rather than on
 * a laptop, because it needs a few thousand outbound requests and the result
 * has to be committed to be useful.
 */
import { writeFileSync } from "node:fs";

const ENDPOINT = "https://api.openbeta.io/";
const UTAH = "ee1d37e7-dc41-5c26-a358-5d51af01f499";
const BATCH = 15;
const MIN_ROUTES = 3;

interface RawArea {
  uuid?: string;
  areaName?: string;
  totalClimbs?: number;
  pathTokens?: string[];
  metadata?: { lat?: number; lng?: number };
  children?: { uuid?: string; totalClimbs?: number }[];
}

const FIELDS = `uuid areaName totalClimbs pathTokens metadata { lat lng } children { uuid totalClimbs }`;

async function fetchBatch(ids: string[]): Promise<RawArea[]> {
  const query = `query {${ids.map((id, i) => `a${i}: area(uuid:"${id}") { ${FIELDS} }`).join(" ")}}`;

  for (let attempt = 0; attempt < 3; attempt += 1) {
    try {
      const response = await fetch(ENDPOINT, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ query }),
      });
      if (!response.ok) {
        await new Promise((r) => setTimeout(r, 2500));
        continue;
      }
      const body = (await response.json()) as { data?: Record<string, RawArea | null> };
      return Object.values(body.data ?? {}).filter((a): a is RawArea => a !== null);
    } catch {
      await new Promise((r) => setTimeout(r, 2500));
    }
  }
  return [];
}

/** Strip anything that would need escaping in the generated file. */
function clean(text: string): string {
  return text
    .replace(/[^\x20-\x7E]/g, " ")
    .replace(/["'\\]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

async function main() {
  const queue: string[] = [UTAH];
  const seen = new Set<string>();
  const leaves: { uuid: string; name: string; region: string; lat: number; lon: number; routes: number }[] = [];
  let visited = 0;

  while (queue.length > 0) {
    const batch: string[] = [];
    while (batch.length < BATCH && queue.length > 0) {
      const id = queue.shift()!;
      if (!seen.has(id)) {
        seen.add(id);
        batch.push(id);
      }
    }
    if (batch.length === 0) break;

    for (const area of await fetchBatch(batch)) {
      const children = (area.children ?? []).filter(
        (c): c is { uuid: string; totalClimbs: number } =>
          typeof c.uuid === "string" && (c.totalClimbs ?? 0) > 0,
      );

      if (children.length > 0) {
        for (const child of children) queue.push(child.uuid);
        continue;
      }

      const lat = area.metadata?.lat;
      const lon = area.metadata?.lng;
      const routes = area.totalClimbs ?? 0;
      if (!area.uuid || !area.areaName || routes < MIN_ROUTES || !lat || !lon) continue;

      // The last two path segments: enough to tell two "North Wall"s apart
      // without printing the whole tree.
      const path = (area.pathTokens ?? []).slice(2, -1).map(clean).filter(Boolean);
      leaves.push({
        uuid: area.uuid.replace(/-/g, ""),
        name: clean(area.areaName).slice(0, 42),
        region: path.slice(-2).join(" / ") || "Utah",
        lat: Math.round(lat * 1e4) / 1e4,
        lon: Math.round(lon * 1e4) / 1e4,
        routes,
      });
    }

    visited += batch.length;
    if (visited % 300 === 0) console.log(`${visited} areas walked, ${leaves.length} crags found`);
    await new Promise((r) => setTimeout(r, 200));
  }

  leaves.sort((a, b) => b.routes - a.routes);

  const regions = [...new Set(leaves.map((l) => l.region))];
  const regionIndex = new Map(regions.map((r, i) => [r, i]));
  const rows = leaves.map((l) => [l.uuid, l.name, regionIndex.get(l.region)!, l.lat, l.lon, l.routes]);

  const header = `/* Generated by scripts/import-openbeta-areas.ts on ${new Date().toISOString().slice(0, 10)}. Data from OpenBeta (openbeta.io), CC0. */\n`;
  const body = `${header}
/** Region labels, referenced by index from each row. */
export const OB_REGIONS: string[] = ${JSON.stringify(regions)};

/** [uuid (no dashes), name, region index, lat, lon, route count] */
export type ObAreaRow = [string, string, number, number, number, number];

export const OB_AREAS: ObAreaRow[] = ${JSON.stringify(rows)};
`;

  writeFileSync(new URL("../src/lib/data/openbetaAreas.ts", import.meta.url), body);
  console.log(`Wrote ${leaves.length} crags across ${regions.length} regions.`);
}

void main();
