/* Generated by scripts/import-openbeta-areas.ts. Data from OpenBeta (openbeta.io), CC0. */

/** Region labels, referenced by index from each row. */
export const OB_REGIONS: string[] = [];

/** [uuid (no dashes), name, region index, lat, lon, route count] */
export type ObAreaRow = [string, string, number, number, number, number];

export const OB_AREAS: ObAreaRow[] = [];
