/* Generated by scripts/import-osm-trails.ts. Data © OpenStreetMap contributors, ODbL. */

/**
 * [osmId, name, activityMask, lat, lon, county, distanceMi*10, gainFt, elevationFt, surface]
 *
 * `osmId` is prefixed "r" for a relation and "w" for a way, so the row can
 * link back to the feature it came from. `county` is empty when the importer
 * could not name one; the builder fills it in.
 */
export type OsmTrailRow = [
  string, string, number, number, number, string, number, number, number, string,
];

export const OSM_TRAILS: OsmTrailRow[] = [];
